packages:
  - apps/*
  - configs/*
  - packages/*

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@nestjs/core'
  - argon2
  - esbuild

allowBuilds:
  '@biomejs/biome': true
  '@scarf/scarf': true
  argon2: true
  msgpackr-extract: true
  unrs-resolver: true

catalog:
  '@aws-sdk/client-s3': 3.1111.0
  '@aws-sdk/s3-request-presigner': 3.1111.0
  '@biomejs/biome': 1.9.4
  '@fastify/cookie': 11.1.2
  '@fastify/helmet': 13.1.0
  '@fastify/multipart': 10.1.1
  '@nestjs/bullmq': 11.0.5
  '@nestjs/cli': 11.0.24
  '@nestjs/common': 11.1.29
  '@nestjs/config': 4.0.4
  '@nestjs/core': 11.1.29
  '@nestjs/jwt': 11.0.2
  '@nestjs/platform-fastify': 11.1.29
  '@nestjs/schematics': 11.1.0
  '@nestjs/swagger': 11.4.6
  '@nestjs/testing': 11.1.29
  '@nestjs/throttler': 6.5.0
  '@nestjs/typeorm': 11.0.0
  '@types/handlebars': 4.0.40
  '@types/ioredis': 4.28.10
  '@types/jest': 30.0.0
  '@types/node': 24.12.4
  '@types/nodemailer': 8.0.1
  '@types/qrcode': 1.5.6
  '@types/speakeasy': 2.0.10
  '@types/supertest': 7.2.0
  '@types/uuid': 10.0.0
  argon2: 0.45.1
  bullmq: 6.0.11
  class-transformer: 0.5.1
  class-validator: 0.15.1
  date-fns: 4.4.0
  dotenv: 16.4.7
  fastify: 5.11.3
  handlebars: 4.7.9
  ioredis: 5.11.1
  jest: 30.4.2
  joi: 18.2.3
  nanoid: 3.3.12
  nodemailer: 9.0.5
  pg: 8.23.0
  pg-mem: 3.0.14
  qrcode: 1.5.4
  reflect-metadata: 0.2.2
  rxjs: 7.8.2
  source-map-support: 0.5.21
  speakeasy: 2.0.0
  supertest: 7.2.2
  ts-jest: 29.4.11
  ts-loader: 9.6.0
  ts-node: 10.9.2
  tsconfig-paths: 4.2.0
  turbo: 2.10.11
  typeorm: 1.1.0
  typescript: 5.9.3
  uuid: 11.1.1
  winston: 3.19.0
  winston-daily-rotate-file: 5.0.0
