packages:
  - apps/*
  - configs/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - argon2
  - esbuild

allowBuilds:
  '@scarf/scarf': true
  argon2: true
  msgpackr-extract: true
  unrs-resolver: true
